var hierarchy =
[
    [ "AccuracyScoring", "class_accuracy_scoring.html", null ],
    [ "Agency", "class_agency.html", null ],
    [ "Agnecy", "class_agnecy.html", null ],
    [ "BalloonPosition", "class_balloon_position.html", null ],
    [ "Class", "class_class.html", null ],
    [ "ColorList_Text", "class_color_list___text.html", null ],
    [ "ColorListBubble", "class_color_list_bubble.html", null ],
    [ "ColorPosition", "class_color_position.html", null ],
    [ "Content", "class_content.html", null ],
    [ "ContentRank", "class_content_rank.html", null ],
    [ "ContentsInfo", "struct_contents_info.html", null ],
    [ "ContentsList", "struct_contents_list.html", null ],
    [ "Country", "class_country.html", null ],
    [ "DocumentResponse< T >", "class_document_response.html", null ],
    [ "DocumentWrapper", "class_document_wrapper.html", null ],
    [ "DualEndingData", "class_dual_ending_data.html", null ],
    [ "DualRank", "class_dual_rank.html", null ],
    [ "EndingData", "class_ending_data.html", null ],
    [ "Feedback", "class_feedback.html", null ],
    [ "FlagList", "struct_flag_list.html", null ],
    [ "Function", "struct_function.html", null ],
    [ "GameRecord", "class_game_record.html", [
      [ "DualGameRecord", "class_dual_game_record.html", null ],
      [ "SingleGameRecord", "class_single_game_record.html", null ]
    ] ],
    [ "GraphData", "class_graph_data.html", null ],
    [ "IEqualityComparer", null, [
      [ "useful.Team.TeamComparer", "classuseful_1_1_team_1_1_team_comparer.html", null ]
    ] ],
    [ "IPointerDownHandler", null, [
      [ "RectConMs", "class_rect_con_ms.html", null ]
    ] ],
    [ "IPointerUpHandler", null, [
      [ "RectConMs", "class_rect_con_ms.html", null ]
    ] ],
    [ "ITouchObject", "interface_i_touch_object.html", [
      [ "Basketball.TouchGoalController", "class_basketball_1_1_touch_goal_controller.html", null ],
      [ "Bubble.BubbleBackgroundTouch", "class_bubble_1_1_bubble_background_touch.html", null ],
      [ "Bubble.BubbleTouch", "class_bubble_1_1_bubble_touch.html", null ],
      [ "ButtonTouchController", "class_button_touch_controller.html", null ],
      [ "Card.Card", "class_card_1_1_card.html", null ],
      [ "Card.CardBackgroundTouch", "class_card_1_1_card_background_touch.html", null ],
      [ "HotAirBalloon.BalloonTouchController", "class_hot_air_balloon_1_1_balloon_touch_controller.html", null ],
      [ "LicensePageTouch", "class_license_page_touch.html", null ],
      [ "Quickness.TouchObjectController", "class_quickness_1_1_touch_object_controller.html", null ],
      [ "Tennis.BallTouchController", "class_tennis_1_1_ball_touch_controller.html", null ],
      [ "TouchPrefabsController", "class_touch_prefabs_controller.html", null ]
    ] ],
    [ "JsonConverter", null, [
      [ "MongoDbDateTimeConverter", "class_mongo_db_date_time_converter.html", null ],
      [ "MongoDbObjectIdConverter", "class_mongo_db_object_id_converter.html", null ]
    ] ],
    [ "LocalizedString", "class_localized_string.html", null ],
    [ "MongoResponse< T >", "class_mongo_response.html", null ],
    [ "MonoBehaviour", null, [
      [ "AgencyController", "class_agency_controller.html", null ],
      [ "BackgroundMoveController", "class_background_move_controller.html", null ],
      [ "BaseService", "class_base_service.html", [
        [ "AgencyService", "class_agency_service.html", null ],
        [ "ContentService", "class_content_service.html", null ],
        [ "FeedbackService", "class_feedback_service.html", null ],
        [ "GameRecordService", "class_game_record_service.html", null ],
        [ "RankSummaryService", "class_rank_summary_service.html", null ]
      ] ],
      [ "Basketball.BasketballManager", "class_basketball_1_1_basketball_manager.html", null ],
      [ "Basketball.TouchGoalController", "class_basketball_1_1_touch_goal_controller.html", null ],
      [ "Bubble.BubbleBackgroundTouch", "class_bubble_1_1_bubble_background_touch.html", null ],
      [ "Bubble.BubbleManager", "class_bubble_1_1_bubble_manager.html", null ],
      [ "Bubble.BubbleTouch", "class_bubble_1_1_bubble_touch.html", null ],
      [ "ButtonTouchController", "class_button_touch_controller.html", null ],
      [ "Card.Card", "class_card_1_1_card.html", null ],
      [ "Card.CardBackgroundTouch", "class_card_1_1_card_background_touch.html", null ],
      [ "Card.CardController", "class_card_1_1_card_controller.html", null ],
      [ "Card.CardVsController", "class_card_1_1_card_vs_controller.html", null ],
      [ "Card.ChildObjectsFlow", "class_card_1_1_child_objects_flow.html", null ],
      [ "ContentController", "class_content_controller.html", null ],
      [ "CountryScript", "class_country_script.html", null ],
      [ "CreateAndRemoveUser", "class_create_and_remove_user.html", null ],
      [ "DropdownController", "class_dropdown_controller.html", null ],
      [ "EndingGetData", "class_ending_get_data.html", null ],
      [ "EndingRanking", "class_ending_ranking.html", null ],
      [ "EndingUI", "class_ending_u_i.html", null ],
      [ "FeedbackController", "class_feedback_controller.html", null ],
      [ "FlagListController", "class_flag_list_controller.html", null ],
      [ "GameRecordController", "class_game_record_controller.html", null ],
      [ "HotAirBalloon.BalloonTouchController", "class_hot_air_balloon_1_1_balloon_touch_controller.html", null ],
      [ "HotAirBalloon.HotAirBalloonManager", "class_hot_air_balloon_1_1_hot_air_balloon_manager.html", null ],
      [ "JapanProject.SettingManager", "class_japan_project_1_1_setting_manager.html", null ],
      [ "KeyPadController", "class_key_pad_controller.html", null ],
      [ "LicensePageTouch", "class_license_page_touch.html", null ],
      [ "LoadingLauncher", "class_loading_launcher.html", null ],
      [ "LoadingManager", "class_loading_manager.html", null ],
      [ "LoadingMotion", "class_loading_motion.html", null ],
      [ "MS500DLL", "class_m_s500_d_l_l.html", null ],
      [ "MS500sdk", "class_m_s500sdk.html", null ],
      [ "MoveSceneController", "class_move_scene_controller.html", null ],
      [ "OlympicsGameManager", "class_olympics_game_manager.html", null ],
      [ "ProfileListController", "class_profile_list_controller.html", null ],
      [ "Quickness.QuicknessManager", "class_quickness_1_1_quickness_manager.html", null ],
      [ "Quickness.TouchObjectController", "class_quickness_1_1_touch_object_controller.html", null ],
      [ "RankSummaryController", "class_rank_summary_controller.html", null ],
      [ "RankingMoveCotroller", "class_ranking_move_cotroller.html", null ],
      [ "RankingPrefabData", "class_ranking_prefab_data.html", null ],
      [ "RectConMs", "class_rect_con_ms.html", null ],
      [ "SelectContentsController", "class_select_contents_controller.html", null ],
      [ "SessionManager", "class_session_manager.html", null ],
      [ "SettingContentsController", "class_setting_contents_controller.html", null ],
      [ "SettingManager", "class_setting_manager.html", null ],
      [ "SettingPageManager", "class_setting_page_manager.html", null ],
      [ "Singleton< T >", "class_singleton.html", null ],
      [ "TeamClickMotion", "class_team_click_motion.html", null ],
      [ "Tennis.BallMoveController", "class_tennis_1_1_ball_move_controller.html", null ],
      [ "Tennis.BallRotation", "class_tennis_1_1_ball_rotation.html", null ],
      [ "Tennis.BallTouchController", "class_tennis_1_1_ball_touch_controller.html", null ],
      [ "Tennis.CharacterMove", "class_tennis_1_1_character_move.html", null ],
      [ "TextPosition", "class_text_position.html", null ],
      [ "TouchPrefabsController", "class_touch_prefabs_controller.html", null ],
      [ "UserPageController", "class_user_page_controller.html", null ],
      [ "useful.Countdown", "classuseful_1_1_countdown.html", null ],
      [ "useful.ESCManager", "classuseful_1_1_e_s_c_manager.html", null ],
      [ "useful.Team.ScoreManager", "classuseful_1_1_team_1_1_score_manager.html", null ],
      [ "useful.TouchEffectController", "classuseful_1_1_touch_effect_controller.html", null ],
      [ "useful.UiAnimation", "classuseful_1_1_ui_animation.html", null ],
      [ "useful.UpDownTimer", "classuseful_1_1_up_down_timer.html", null ],
      [ "useful.UserDataController", "classuseful_1_1_user_data_controller.html", null ]
    ] ],
    [ "MyRank", "class_my_rank.html", null ],
    [ "RankSummaryController.MyRankData", "class_rank_summary_controller_1_1_my_rank_data.html", null ],
    [ "PasswordHelper", "class_password_helper.html", null ],
    [ "People", "class_people.html", null ],
    [ "ProfileList", "struct_profile_list.html", null ],
    [ "Rank", "class_rank.html", null ],
    [ "RankSummary", "class_rank_summary.html", null ],
    [ "RecordDetail", "class_record_detail.html", null ],
    [ "useful.Team.Score", "classuseful_1_1_team_1_1_score.html", null ],
    [ "Singleton< Ms500Manager >", "class_singleton.html", [
      [ "Ms500Manager", "class_ms500_manager.html", null ]
    ] ],
    [ "SpeedScoring", "class_speed_scoring.html", null ],
    [ "Student", "class_student.html", null ],
    [ "useful.Team.TeamDictionarySetter< T >", "classuseful_1_1_team_1_1_team_dictionary_setter.html", null ],
    [ "useful.Team.TeamDictionarySetter< useful.Team.Score >", "classuseful_1_1_team_1_1_team_dictionary_setter.html", null ],
    [ "TopRank", "class_top_rank.html", null ],
    [ "TouchEvent", "class_touch_event.html", null ],
    [ "Winner", "struct_winner.html", null ]
];