var namespace_lean_1_1_localization =
[
    [ "ILocalizationHandler", "interface_lean_1_1_localization_1_1_i_localization_handler.html", "interface_lean_1_1_localization_1_1_i_localization_handler" ],
    [ "LeanDebugLocalization", "class_lean_1_1_localization_1_1_lean_debug_localization.html", "class_lean_1_1_localization_1_1_lean_debug_localization" ],
    [ "LeanLanguage", "class_lean_1_1_localization_1_1_lean_language.html", "class_lean_1_1_localization_1_1_lean_language" ],
    [ "LeanLanguageCSV", "class_lean_1_1_localization_1_1_lean_language_c_s_v.html", "class_lean_1_1_localization_1_1_lean_language_c_s_v" ],
    [ "LeanLanguageNameAttribute", "class_lean_1_1_localization_1_1_lean_language_name_attribute.html", null ],
    [ "LeanLocalization", "class_lean_1_1_localization_1_1_lean_localization.html", "class_lean_1_1_localization_1_1_lean_localization" ],
    [ "LeanLocalizedAudioSource", "class_lean_1_1_localization_1_1_lean_localized_audio_source.html", "class_lean_1_1_localization_1_1_lean_localized_audio_source" ],
    [ "LeanLocalizedBehaviour", "class_lean_1_1_localization_1_1_lean_localized_behaviour.html", "class_lean_1_1_localization_1_1_lean_localized_behaviour" ],
    [ "LeanLocalizedDropdown", "class_lean_1_1_localization_1_1_lean_localized_dropdown.html", "class_lean_1_1_localization_1_1_lean_localized_dropdown" ],
    [ "LeanLocalizedImage", "class_lean_1_1_localization_1_1_lean_localized_image.html", "class_lean_1_1_localization_1_1_lean_localized_image" ],
    [ "LeanLocalizedRenderer", "class_lean_1_1_localization_1_1_lean_localized_renderer.html", "class_lean_1_1_localization_1_1_lean_localized_renderer" ],
    [ "LeanLocalizedSpriteRenderer", "class_lean_1_1_localization_1_1_lean_localized_sprite_renderer.html", "class_lean_1_1_localization_1_1_lean_localized_sprite_renderer" ],
    [ "LeanLocalizedText", "class_lean_1_1_localization_1_1_lean_localized_text.html", "class_lean_1_1_localization_1_1_lean_localized_text" ],
    [ "LeanLocalizedTextFont", "class_lean_1_1_localization_1_1_lean_localized_text_font.html", "class_lean_1_1_localization_1_1_lean_localized_text_font" ],
    [ "LeanLocalizedTextMesh", "class_lean_1_1_localization_1_1_lean_localized_text_mesh.html", "class_lean_1_1_localization_1_1_lean_localized_text_mesh" ],
    [ "LeanLocalizedTextMeshFont", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_font.html", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_font" ],
    [ "LeanLocalizedTextMeshPro", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro.html", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro" ],
    [ "LeanLocalizedTextMeshProFont", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro_font.html", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro_font" ],
    [ "LeanLocalizedTextMeshProUGUI", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro_u_g_u_i.html", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro_u_g_u_i" ],
    [ "LeanLocalizedTextMeshProUGUIFont", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro_u_g_u_i_font.html", "class_lean_1_1_localization_1_1_lean_localized_text_mesh_pro_u_g_u_i_font" ],
    [ "LeanLocalizedTMP_Dropdown", "class_lean_1_1_localization_1_1_lean_localized_t_m_p___dropdown.html", "class_lean_1_1_localization_1_1_lean_localized_t_m_p___dropdown" ],
    [ "LeanLocalToken", "class_lean_1_1_localization_1_1_lean_local_token.html", "class_lean_1_1_localization_1_1_lean_local_token" ],
    [ "LeanPhrase", "class_lean_1_1_localization_1_1_lean_phrase.html", "class_lean_1_1_localization_1_1_lean_phrase" ],
    [ "LeanPrefab", "class_lean_1_1_localization_1_1_lean_prefab.html", "class_lean_1_1_localization_1_1_lean_prefab" ],
    [ "LeanSource", "class_lean_1_1_localization_1_1_lean_source.html", "class_lean_1_1_localization_1_1_lean_source" ],
    [ "LeanToken", "class_lean_1_1_localization_1_1_lean_token.html", "class_lean_1_1_localization_1_1_lean_token" ],
    [ "LeanTranslation", "class_lean_1_1_localization_1_1_lean_translation.html", "class_lean_1_1_localization_1_1_lean_translation" ],
    [ "LeanTranslationNameAttribute", "class_lean_1_1_localization_1_1_lean_translation_name_attribute.html", null ]
];